-- 1
SELECT BOOKNAME FROM BOOK WHERE BOOKID = 1;
--2
SELECT BOOKNAME FROM BOOK WHERE PRICE >= 20000;
--3
SELECT SUM(saleprice) FROM ORDERS WHERE CUSTID = 1;
--4
SELECT COUNT(*) FROM ORDERS WHERE CUSTID = 1;

--1
SELECT COUNT(*) FROM BOOK;
--2
SELECT COUNT(DISTINCT publisher) FROM BOOK;
--3
SELECT NAME, ADDRESS FROM CUSTOMER;
--4
SELECT ORDERID FROM ORDERS WHERE orderdate > '14/07/03' AND orderdate < '14/07/08';
--5
SELECT ORDERID FROM ORDERS WHERE NOT(orderdate > '14/07/03' AND orderdate < '14/07/08');
--6
SELECT NAME, ADDRESS FROM CUSTOMER WHERE NAME LIKE '김%';
--7
SELECT NAME, ADDRESS FROM CUSTOMER WHERE NAME LIKE '김%아';

SELECT * FROM CUSTOMER;