SELECT CUSTID, (SELECT ADDRESS FROM CUSTOMER CS
                WHERE CS.CUSTID=OD.CUSTID) "ADDRESS", SUM(SALEPRICE) "TOTAL"
FROM ORDERS OD
GROUP BY OD.CUSTID;

SELECT CS.NAME, S
FROM (SELECT CUSTID, AVG(SALEPRICE) S
        FROM ORDERS
        GROUP BY CUSTID) OD, CUSTOMER CS
WHERE CS.CUSTID=OD.CUSTID

SELECT SUM(SALEPRICE) AS TOTAL
FROM ORDERS OD
WHERE EXISTS (SELECT *
            FROM CUSTOMER CS
            WHERE CUSTID <= 3 AND CS.CUSTID=OD.CUSTID);

SELECT SALEPRICE FROM ORDERS
WHERE CUSTID <= 3